export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const ORDER_PLACED = 'ORDER_PLACED';
export const ORDER_SUCCESSFUL = 'ORDER_SUCCESSFUL';
export const ORDER_FAILED = 'ORDER_FAILED';
